Iter5
egor-zakharov/tiny-url pull request #6
Opened 2024-03-30 16:34 UTC by egor-zakharov

2024-04-03 21:18 UTC, avhitrov requested changes
Нет проверки входных данных. Data Race при работе со стораджем. Подробности в комментариях.

2024-04-03 21:18 UTC, avhitrov commented on cmd/shortener/main.go
> +	}
Будет правильным сначала проверить переданные данные на соответствие формату url. Хотя бы через url.Parse()

2024-04-03 21:18 UTC, avhitrov commented on cmd/shortener/main.go
> +var urls = make(map[string]string)
Мапа является потоконебезопасной структурой. В конкурентной среде (а вебсервер таковой является) все обращения к ней необходимо обвешивать блокировкой. Можно использовать `sync.Mutex`, `sync.RWMutex` или потокобезопасной мапой `sync.Map`.

https://t.me/bushigo/24

Иначе получаем:
```
==================
WARNING: DATA RACE
Write at 0x00c0000f89c8 by goroutine 7:
  main.post()
      C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:26 +0x193
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x525
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x1eb
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Apps/Go/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c0000f89c8 by goroutine 66:
  main.get()
      C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:36 +0x9b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x525
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x1eb
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Apps/Go/src/net/http/server.go:3086 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3086 +0x80c
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3239 +0x204
  main.main()
      C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:61 +0xec

Goroutine 66 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3086 +0x80c
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3239 +0x204
  main.main()
      C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:61 +0xec
==================
```
и последующую панику:
```
fatal error: 2024/04/04 00:12:27 "GET http://localhost:8080/wuY29tLw HTTP/1.1" from [::1]:56036 - 307 0B in 0s
concurrent map read and map write
2024/04/04 00:12:27 "GET http://localhost:8080/wuY29tLw HTTP/1.1" from [::1]:56065 - 307 0B in 0s

goroutine 1682 [running]:
main.get({0x47864010, 0xc0006ae700}, 0xc000695590?)
        C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:36 +0x8b
net/http.HandlerFunc.ServeHTTP(0x14054d8e0, {0x47864010, 0xc0006ae700}, 0xc00018abec?)
        C:/Apps/Go/src/net/http/server.go:2136 +0x48
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0000f6060, {0x47864010, 0xc0006ae700}, 0xc00053f100)
        C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x526
net/http.HandlerFunc.ServeHTTP(0xc00008a180, {0x47864010, 0xc0006ae700}, 0xc0002ef868?)
        C:/Apps/Go/src/net/http/server.go:2136 +0x48
github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1({0x1405b8af0, 0xc0002c29a0}, 0xc00053f000)
        C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/logger.go:55 +0x1ec
net/http.HandlerFunc.ServeHTTP(0xc000088f00, {0x1405b8af0, 0xc0002c29a0}, 0x140482430?)
        C:/Apps/Go/src/net/http/server.go:2136 +0x48
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0000f6060, {0x1405b8af0, 0xc0002c29a0}, 0xc00053ef00)
        C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67c
net/http.serverHandler.ServeHTTP({0xc000089f20?}, {0x1405b8af0, 0xc0002c29a0}, 0xc00053ef00)
        C:/Apps/Go/src/net/http/server.go:2938 +0x2a2
net/http.(*conn).serve(0xc000333680, {0x1405b91a0, 0xc000089110})
        C:/Apps/Go/src/net/http/server.go:2009 +0xc25
created by net/http.(*Server).Serve in goroutine 1
        C:/Apps/Go/src/net/http/server.go:3086 +0x80d

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0xc58e78, 0x72)
        C:/Apps/Go/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0000a0e38, 0x0?, 0x0)
        C:/Apps/Go/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.execIO(0xc0000a0c98, 0xc000295910)
        C:/Apps/Go/src/internal/poll/fd_windows.go:175 +0x271
internal/poll.(*FD).acceptOne(0xc0000a0c80, 0x264, {0xc00015b0e0, 0x2, 0x2}, 0xc0000a0c98)
        C:/Apps/Go/src/internal/poll/fd_windows.go:944 +0xda
internal/poll.(*FD).Accept(0xc0000a0c80, 0xc000295b78)
        C:/Apps/Go/src/internal/poll/fd_windows.go:978 +0x2fa
net.(*netFD).accept(0xc0000a0c80)
        C:/Apps/Go/src/net/fd_windows.go:166 +0x69
net.(*TCPListener).accept(0xc0000965e0)
        C:/Apps/Go/src/net/tcpsock_posix.go:152 +0x3e
net.(*TCPListener).Accept(0xc0000965e0)
        C:/Apps/Go/src/net/tcpsock.go:315 +0x65
net/http.(*Server).Serve(0xc0000fe000, {0x1405b8cd0, 0xc0000965e0})
        C:/Apps/Go/src/net/http/server.go:3056 +0x57f
net/http.(*Server).ListenAndServe(0xc0000fe000)
        C:/Apps/Go/src/net/http/server.go:2985 +0xbd
net/http.ListenAndServe(...)
        C:/Apps/Go/src/net/http/server.go:3239
main.main()
        C:/work/src/github.com/egor-zakharov/tiny-url/cmd/shortener/main.go:61 +0x205
```

2024-04-04 20:06 UTC, egor-zakharov commented on cmd/shortener/main.go
> +	}
Реализовал отдельный метод на [валидацию ](https://github.com/egor-zakharov/tiny-url/pull/6/files#diff-015c371a3faa14febae982c5950320cffd196e63051d9e6e9b493beac50a44c9R44)requestBody по [регулярке](https://github.com/egor-zakharov/tiny-url/pull/6/files#diff-015c371a3faa14febae982c5950320cffd196e63051d9e6e9b493beac50a44c9R12)

2024-04-04 20:07 UTC, egor-zakharov commented on cmd/shortener/main.go
> +var urls = make(map[string]string)
вынес в отдельный [storage](https://github.com/egor-zakharov/tiny-url/pull/6/files#diff-2647f10de49d53c505658fecad1695061d4bcaf72165044664a306b781d1c09fR13)

2024-04-04 23:11 UTC, avhitrov approved these changes
Годный рефакторинг, все отлично!

2024-04-09 18:00 UTC, merged